#ifndef NOOSKEWL_ENGINE_H
#define NOOSKEWL_ENGINE_H

#include "Nooskewl_Engine/brain.h"
#include "Nooskewl_Engine/cpa.h"
#include "Nooskewl_Engine/dllist.h"
#include "Nooskewl_Engine/engine.h"
#include "Nooskewl_Engine/error.h"
#include "Nooskewl_Engine/font.h"
#include "Nooskewl_Engine/image.h"
#include "Nooskewl_Engine/internal.h"
#include "Nooskewl_Engine/log.h"
#include "Nooskewl_Engine/main.h"
#include "Nooskewl_Engine/map.h"
#include "Nooskewl_Engine/map_entity.h"
#include "Nooskewl_Engine/map_logic.h"
#include "Nooskewl_Engine/mml.h"
#include "Nooskewl_Engine/module.h"
#include "Nooskewl_Engine/player_brain.h"
#include "Nooskewl_Engine/sample.h"
#include "Nooskewl_Engine/speech.h"
#include "Nooskewl_Engine/sprite.h"
#include "Nooskewl_Engine/tilemap.h"
#include "Nooskewl_Engine/tween.h"
#include "Nooskewl_Engine/types.h"
#include "Nooskewl_Engine/util.h"
#include "Nooskewl_Engine/vertex_cache.h"
#include "Nooskewl_Engine/widgets.h"
#include "Nooskewl_Engine/xml.h"

#endif // NOOSKEWL_ENGINE_HNooskewl_Engine.h